apiVersion: apps/v1
kind: Deployment
metadata:
  name: pride-chatbot
  labels:
    app: pride-chatbot
spec:
  replicas: $k8s_replicas
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: pride-chatbot
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: $k8s_rollingupdate_maxUnavailable
  template:
    metadata:
      labels:
        app: pride-chatbot
    spec:
      imagePullSecrets:
        - name: $DOCKER_PULL_SECRET
      containers:
        - name: pride-chatbot
          image: $IMAGE
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /pride/chatbot
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /pride/chatbot
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: pride-chatbot-service
spec:
  selector:
    app: pride-chatbot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
